App_admin/urls.py
from django.urls import path
from App_admin import views

app_name = 'App_admin'

urlpatterns = [
    path('admin-login-system/', views.admin_login_system, name='admin-login-system'),
    path('', views.admin_dashboard, name='admin-dashboard'),
    path('all-users/', views.allUsers, name='all-users'),
    path('delete-user/<int:delete_id>/', views.delete_user, name='delete-user'),
    path('create-user/', views.create_user_by_admin, name='create-user'),
    path('all-profile-view/', views.allUserProfile, name='all-profile-view'),
    path('create-userProfile-by-admin', views.create_userProfile_by_admin, name='create-userProfile-by-admin'),
    path('single-user-profile/<str:username>/', views.single_user_profile_showcase, name='single-user-profile'),
    path('admin-booking-view/', views.admin_booking_view, name='admin-booking-view'),
    path('update-booking-status/', views.update_booking_status,
         name='update-booking-status'),
    path('admin-campaign-view/', views.admin_campaign_view, name='admin-campaign-view'),
    path('admin-comment-view/', views.admin_comment_view, name='admin-comment-view'),
    path('admin-service-view/', views.admin_service_view, name='admin-service-view'),
    path('admin-service-update-view/<int:pk>/', views.admin_service_update_view, name='admin-service-update-view'),
    path('admin-service-update-status-view/', views.admin_service_update_status_view, name='admin-service-update-status-view'),
    path('admin-gallery-view/', views.admin_gallery_view, name='admin-gallery-view'),
    path('admin-galleryImage-delete-view/<int:deleteID>/', views.admin_galleryImage_delete_view,
         name='admin-galleryImage-delete-view'),
    path('admin-group-view/', views.admin_group_view, name='admin-group-view'),
    path('admin-group-add-view/', views.admin_group_add_view, name='admin-group-add-view'),
    path('admin-group-delete-view/<str:name>/', views.admin_group_delete_view, name='admin-group-delete-view'),
    path('admin-chat-room/', views.admin_chat_room, name='admin-chat-room'),
    path('admin-see-messages/<int:pk>/', views.admin_see_messages, name='admin-see-messages'),
    path('admin-get-messages/<int:room>/', views.admin_get_messages, name='admin-get-messages'),
    path('admin-response-message/', views.admin_message_send, name='admin-response-message'),
]

App_auth/urls.py
from django.urls import path
from App_auth.views import *

app_name = 'App_auth'

urlpatterns = [
    path('register/', registerView, name='register'),
    path('login/', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
]

SmartGarageService_and_internal_messaging/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from SmartGarageService_and_internal_messaging import developers

urlpatterns = [
    # You shouldn't 
    path('developers/', developers.developersView, name='developers'),
    path('super-admin/', admin.site.urls),
    path('accounts/', include('App_auth.urls')),
    path('', include('App_main.urls')),
    path('admin/', include('App_admin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


App_admin/models.py
from django.db import models

# Create your models here.

App_admin/forms.py
from django import forms

App_admin/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test

from App_auth.forms import AddressModelForm, ProfileModelForm, SignupForm
from App_auth.models import *
from App_main.forms import CampaignModelForm, ServicesModelForm, GalleryModelForm, ServicesUpdateModelForm
from App_main.models import BookingModel, ServicesModel, CommentOnCampaign, CampaignModel, GalleryModel, ChatRoom, \
    MessageModel


# Create your views here.
def is_admin(user):
    return user.groups.filter(name='ADMIN').exists()


def is_customer(user):
    return user.groups.filter(name='CUSTOMER').exists()


def total_client(userList, total):
    if len(userList) == 0:
        return total
    else:
        if is_customer(userList[0]):
            total += 1
        userList.remove(userList[0])
        return total_client(userList, total)


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def admin_dashboard(request):
    try:
        profile = ProfileModel.objects.get(user=request.user)
    except:
        profile = None
    total_served_order = BookingModel.objects.filter(status='Service Provided')
    total_pending_order = BookingModel.objects.filter(status='Service Processing')
    total_order = BookingModel.objects.all()
    total_groups = Group.objects.all()
    total_comment = CommentOnCampaign.objects.all()
    all_user = User.objects.all()
    total_user = total_client(list(all_user), 0)
    services = ServicesModel.objects.all()
    content = {
        'profile': profile,
        'total_served_order': total_served_order,
        'total_pending_order': total_pending_order,
        'total_order': total_order,
        'total_group': total_groups,
        'total_comment': total_comment,
        'total_user': total_user,
        'total_services': services,
    }
    return render(request, 'App_admin/dashboard.html', context=content)


def admin_login_system(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user_email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=user_email, password=password)
            if user:
                login(request, user)
                if is_admin(user):
                    return HttpResponseRedirect(reverse('App_admin:admin-dashboard'))
                return HttpResponseRedirect(reverse('App_admin:admin-login-system'))
    content = {
        'form': form
    }
    return render(request, 'App_admin/login_page.html', context=content)


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def allUsers(request):
    users = User.objects.filter(is_superuser=False)
    content = {
        'users': users
    }
    return render(request, 'App_admin/all_users.html', context=content)


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def create_user_by_admin(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = User(username=username)
    user.set_password(password)
    user.is_superuser = False
    user.is_active = True
    user.is_staff = False
    user.save()

    return HttpResponseRedirect(reverse('App_admin:all-users'))


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def delete_user(request, delete_id):
    user = User.objects.get(id=delete_id)
    user.delete()
    return HttpResponseRedirect(reverse('App_admin:all-users'))


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def allUserProfile(request):
    profiles = ProfileModel.objects.filter(user__is_superuser=False)
    users = User.objects.filter(is_superuser=False)
    profileForm = ProfileModelForm()
    content = {
        'profiles': profiles,
        'users': users,
        'profileForm': profileForm,
    }
    return render(request, 'App_admin/all_profile.html', context=content)


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def create_userProfile_by_admin(request):
    if request.method == 'POST':
        userFor = request.POST.get('user')
        user = User.objects.get(username=userFor)
        profileForm = ProfileModelForm(request.POST, request.FILES)
        if profileForm.is_valid():
            thisProfile = profileForm.save(commit=False)
            thisProfile.user = user
            thisProfile.save()
            return HttpResponseRedirect(reverse('App_admin:all-profile-view'))
    return HttpResponseRedirect(reverse('App_admin:all-profile-view'))


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def single_user_profile_showcase(request, username):
    user = User.objects.get(username=username)
    profile = ProfileModel.objects.get(user=user)
    userForm = SignupForm(instance=user)
    profileForm = ProfileModelForm(instance=profile)
    if request.method == 'POST':
        userForm = SignupForm(request.post, request.files)
        profileForm = ProfileModelForm(request.post)
        if userForm.is_valid() and profileForm.is_valid():
            u = userForm.save()
            this_profile = profileForm.save(commit=False)
            this_profile.user = u
            this_profile.save()
            return HttpResponseRedirect(reverse('App_admin:single-user-profile', kwargs=u.username))
    content = {
        'userForm': userForm,
        'profileForm': profileForm,
    }
    return render(request, 'App_admin/single_user_profile.html', context=content)


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def admin_booking_view(request):
    bookings = BookingModel.objects.all()
    content = {
        'bookings': bookings
    }
    return render(request, 'App_admin/admin_booking_view.html', context=content)


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def update_booking_status(request):
    if request.method == 'POST':
        bookingID = request.POST.get('bookingID')
        bookingStatus = request.POST.get('status')
        booking = BookingModel.objects.get(id=bookingID)
        booking.status = bookingStatus
        booking.save()
        return HttpResponseRedirect(reverse('App_admin:admin-booking-view'))
    return HttpResponseRedirect(reverse('App_admin:admin-booking-view'))


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def admin_campaign_view(request):
    campaigns = CampaignModel.objects.all()
    add_campaignForm = CampaignModelForm()
    if request.method == 'POST':
        add_campaignForm = CampaignModelForm(data=request.POST)
        if add_campaignForm.is_valid():
            add_campaignForm.save()
    content = {
        'campaigns': campaigns,
        'campForm': add_campaignForm
    }
    return render(request, 'App_admin/admin_campaign_view.html', context=content)


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def admin_comment_view(request):
    comments = CommentOnCampaign.objects.all()
    content = {
        'comments': comments
    }
    return render(request, 'App_admin/admin_comment_view.html', context=content)


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def admin_service_view(request):
    services = ServicesModel.objects.all()
    serviceForm = ServicesModelForm()
    if request.method == 'POST':
        details = request.POST.get('my-service-content')
        serviceForm = ServicesModelForm(request.POST, request.FILES)
        if serviceForm.is_valid():
            serv = serviceForm.save(commit=False)
            serv.details = details
            serv.save()
            return HttpResponseRedirect(reverse('App_admin:admin-service-view'))
    content = {
        'services': services,
        'serviceForm': serviceForm,
    }
    return render(request, 'App_admin/admin_service_view.html', context=content)


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def admin_service_update_view(request, pk):
    serv = ServicesModel.objects.get(id=pk)
    form = ServicesUpdateModelForm(instance=serv)
    if request.method == 'POST':
        details = request.POST.get('my-service-content')
        form = ServicesUpdateModelForm(request.POST, request.FILES, instance=serv)
        if form.is_valid():
            # form.save()
            servForm = form.save(commit=False)
            servForm.details = details
            servForm.save()
            return HttpResponseRedirect(reverse('App_admin:admin-service-view'))
    content = {
        'form': form,
        'service': serv,
    }
    return render(request, 'App_admin/admin-service-update-view.html', context=content)


@login_required(login_url='App_admin:admin-login-system')
@user_passes_test(is_admin)
def admin_service_update_status_view(request):
    if request.method == 'POST':
        status = request.POST.get('status')
        servID = request.POST.get('serviceID')
        service = ServicesModel.objects.get(id=servID)
        service.status = status
        service.save()
        return HttpResponseRedirect(reverse('App_admin:admin-service-view'))


@login_required(login_url='App_admin:admin-login-system')

templates/App_admin/admin_booking_view.html
{% extends 'App_admin/basement.html' %}
{% load crispy_forms_filters %}
{% block admin_base_main %}
    <style>
        .container_content {
            margin: 10px 50px;
        }

        @media screen and (max-width: 720px) {
            .container_content {
                margin: 10px 20px;
            }
        }

        .form-div {
            padding: 10px;
            background: var(--body-bg);
            border-top: none;
            border-bottom: none;
            line-height: 24px;
            color: var(--body-quiet-color);
            width: 100%;
        }

        .form-div form select {
            vertical-align: top;
            height: 24px;
            color: var(--body-fg);
            border: 1px solid var(--border-color);
            border-radius: 4px;
            font-size: 14px;
            padding: 0 0 0 4px;
            margin: 0 0 0 10px;
        }

        /* Table Css */
        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            margin: 0;
            padding: 0;
            width: 100%;
            table-layout: fixed;
        }

        table tr {
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: .35em;
        }

        table th,
        table td {
            padding: .625em;
            text-align: left;
        }

        table th {
            font-size: .85em;
            letter-spacing: .1em;
            text-transform: uppercase;
            text-align: left;
        }

        @media screen and (max-width: 600px) {
            table {
                border: 0;
            }

            table caption {
                font-size: 1.3em;
            }

            table thead {
                border: none;
                clip: rect(0 0 0 0);
                height: 1px;
                margin: -1px;
                overflow: hidden;
                padding: 0;
                position: absolute;
                width: 1px;
            }

            table tr {
                border-bottom: 3px solid #ddd;
                display: block;
                margin-bottom: .625em;
            }

            table td {
                border-bottom: 1px solid #ddd;
                display: block;
                font-size: .8em;
                text-align: right;
            }

            table td::before {
                /*
                * aria-label has no advantage, it won't be read inside a table
                content: attr(aria-label);
                */
                content: attr(data-label);
                float: left;
                font-weight: bold;
                text-transform: uppercase;
            }

            table td:last-child {
                border-bottom: 0;
            }
        }
    </style>
    <div class="main__inner container_content">
        <div class="content">
            <p>
                <span style="font-size: 20px">
                    See All the Bookings
                </span>
            </p>
        </div>
        <div class="form-div">
        </div>
        <div class="container alert alert-light"><h2>Search From Table</h2>
            <br>
            <input id="id-search" type="text" class="form-control" onkeyup="searchFunction()"
                   placeholder="Search with Phone Number">
            <br>
            <table id="id-user-table">
                <thead>
                <tr>
                    <th scope="col" style="color: #666666;">Service Date</th>
                    <th scope="col" style="color: #666666;">Created Date</th>
                    <th scope="col" style="color: #666666;">User</th>
                    <th scope="col" style="color: #666666;">Mobile</th>
                    <th scope="col" style="color: #666666;">Service Type</th>
                    <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                {% for booking in bookings %}
                    <tr>
                        <td data-label="Service Date">
                            {{ booking.booking_date.date }}
                        </td>
                        <td data-label="Created Date">
                            {{ booking.created_date.date }}
                        </td>
                        <td data-label="Username">{{ booking.user }}</td>
                        <td data-label="Mobile">
                            {{ booking.contact_number }}
                        </td>
                        <td data-label="Service Type">{{ booking.service_type.name }}</td>
                        <td data-label="Status">
                            <form action="{% url 'App_admin:update-booking-status' %}" method="post">
                                {% csrf_token %}
                                <input type="number" name="bookingID" value="{{ booking.id }}" style="display: none;">
                                <select name="status" id="id-status">
                                    <option value="{{ booking.status }}">{{ booking.status }}</option>
                                    <option value="Service Processing">Service Processing</option>
                                    <option value="Service Confirmed">Service Confirmed</option>
                                    <option value="Service Provided">Service Provided</option>
                                </select>
                                <button class="btn btn-warning mt-1" type="submit">
                                    update
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        let closer = 0;
        let createUserForm = document.getElementById('id-createuser-form');

        function createUserFormOpener() {
            if (closer === 0) {
                createUserForm.style.display = 'block';
                closer = 1;
            } else {
                createUserForm.style.display = 'none';
                closer = 0;
            }
        }

        function searchFunction() {
            // Declare variables
            var input, filter, table, tr, td, i;
            input = document.getElementById("id-search");
            filter = input.value.toUpperCase();
            table = document.getElementById("id-user-table");
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[3];
                if (td) {
                    if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
{% endblock %}

{% block active_script %}
    Booking.classList.add('mm-active')
{% endblock %}

templates/App_admin/all_users.html
{% extends 'App_admin/basement.html' %}
{% block admin_base_main %}
    <style>
        .container_content {
            margin: 10px 50px;
        }

        @media screen and (max-width: 720px) {
            .container_content {
                margin: 10px 20px;
            }
        }

        .form-div {
            padding: 10px;
            background: var(--body-bg);
            border-top: none;
            border-bottom: none;
            line-height: 24px;
            color: var(--body-quiet-color);
            width: 100%;
        }

        .form-div form select {
            vertical-align: top;
            height: 24px;
            color: var(--body-fg);
            border: 1px solid var(--border-color);
            border-radius: 4px;
            font-size: 14px;
            padding: 0 0 0 4px;
            margin: 0 0 0 10px;
        }

        /* Table Css */
        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            margin: 0;
            padding: 0;
            width: 100%;
            table-layout: fixed;
        }

        table tr {
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: .35em;
        }

        table th,
        table td {
            padding: .625em;
            text-align: left;
        }

        table th {
            font-size: .85em;
            letter-spacing: .1em;
            text-transform: uppercase;
            text-align: left;
        }

        @media screen and (max-width: 600px) {
            table {
                border: 0;
            }

            table caption {
                font-size: 1.3em;
            }

            table thead {
                border: none;
                clip: rect(0 0 0 0);
                height: 1px;
                margin: -1px;
                overflow: hidden;
                padding: 0;
                position: absolute;
                width: 1px;
            }

            table tr {
                border-bottom: 3px solid #ddd;
                display: block;
                margin-bottom: .625em;
            }

            table td {
                border-bottom: 1px solid #ddd;
                display: block;
                font-size: .8em;
                text-align: right;
            }

            table td::before {
                /*
                * aria-label has no advantage, it won't be read inside a table
                content: attr(aria-label);
                */
                content: attr(data-label);
                float: left;
                font-weight: bold;
                text-transform: uppercase;
            }

            table td:last-child {
                border-bottom: 0;
            }
        }
    </style>
    <div class="main__inner container_content">
        <div class="content">
            <p>
                <span style="font-size: 20px">
                    Select custom user to change
                </span>
                <span>
                    <button class="btn-shadow btn btn-info" style="float: right" onclick="createUserFormOpener()">
                        ADD CUSTOM USER
                    </button>
                </span>
            </p>
        </div>
        <div class="form-div">
        </div>
        <div class="container alert alert-light"><h2>Search From Table</h2>
            <br>
            <input id="id-search" type="text" class="form-control" onkeyup="searchFunction()"
                   placeholder="Search with Phone Number">
            <br>
            <table id="id-user-table">
                <thead>
                <tr>
                    <th scope="col" style="color: #666666;">Custom User</th>
                    <th scope="col">Action</th>
                    <th scope="col">Confirm</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td data-label="User">{{ user }}</td>
                        <form action="{% url 'App_admin:delete-user' delete_id=user.id %}" class="form-group">
                            {% csrf_token %}
                            <td data-label="Action">
                                <select name="action" id="id-action{{ user.id }}">
                                    <option value="0">-----------</option>
                                    <option value="1">Delete the user</option>
                                </select>
                            </td>
                            <td data-label="Confirm">
                                <button class="btn-shadow btn btn-dark btn-sm" type="submit" disabled
                                        id="submit-button{{ user.id }}">
                                    Go
                                </button>
                            </td>
                            <script>
                                document.getElementById('id-action{{ user.id }}').addEventListener('change', function () {
                                    console.log(typeof this.value);
                                    if (this.value === '1') {
                                        document.getElementById('submit-button{{ user.id }}').removeAttribute('disabled');
                                    } else {
                                        document.getElementById('submit-button{{ user.id }}').disabled = true;
                                    }
                                });
                            </script>
                        </form>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <script>
                function searchFunction() {
                    // Declare variables
                    var input, filter, table, tr, td, i;
                    input = document.getElementById("id-search");
                    filter = input.value.toUpperCase();
                    table = document.getElementById("id-user-table");
                    tr = table.getElementsByTagName("tr");

                    // Loop through all table rows, and hide those who don't match the search query
                    for (i = 0; i < tr.length; i++) {
                        td = tr[i].getElementsByTagName("td")[0];
                        if (td) {
                            if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                                tr[i].style.display = "";
                            } else {
                                tr[i].style.display = "none";
                            }
                        }
                    }
                }
            </script>
        </div>
    </div>
    <div class="container">
        <div class="add-user-form" style="display: none;" id="id-createuser-form">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6" style="border: 1px solid #000000; border-radius: 7px;">
                    <form action="{% url 'App_admin:create-user' %}" method="post" class="form-group">
                        {% csrf_token %}
                        <legend style="text-align: center; font-size: 20px;">Add new User</legend>
                        <fieldset class="form-group">
                            <div class="form-group">
                                <label for="id_email">Username</label>
                                <input type="text" name="username" id="id_username" class="form-control" required>
                            </div>
                            <br>
                            <div class="form-group">
                                <label for="id_password">Password</label>
                                <input type="password" name="password" id="id_password" class="form-control" required>
                            </div>
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-success" type="submit">
                                Add
                            </button>
                            <button class="btn btn-outline-alternate" type="button" onclick="createUserFormOpener()">
                                <i class="fa fa-times"> Close Form </i>
                            </button>
                        </div>
                    </form>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </div>

    <script>
        let closer = 0;
        let createUserForm = document.getElementById('id-createuser-form');

        function createUserFormOpener() {
            if (closer === 0) {
                createUserForm.style.display = 'block';
                closer = 1;
            } else {
                createUserForm.style.display = 'none';
                closer = 0;
            }
        }
    </script>
{% endblock %}

{% block active_script %}
    dashboard.classList.remove('mm-active')
    Users.classList.add('mm-active')
    UserProfiles.classList.remove('mm-active')
    groups.classList.remove('mm-active')
{% endblock %}

templates/App_admin/single_user_profile.html
{% extends 'App_admin/basement.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block admin_base_main %}
    <div class="main__inner container_content">
        <div class="container">
            <form action="{% url 'App_admin:create-userProfile-by-admin' %}" enctype="multipart/form-data"
                  method="post" class="form-group">
                {% csrf_token %}
                <legend style="text-align: center; font-size: 20px;">Add Profile</legend>
                <fieldset class="form-group">
                    {{ userForm|crispy }}
                    {{ profileForm|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">
                        Add
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
