App_auth/urls.py
from django.urls import path
from App_auth.views import *

app_name = 'App_auth'

urlpatterns = [
    path('register/', registerView, name='register'),
    path('login/', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
]

App_main/urls.py
from django.urls import path
from App_main import views

app_name = 'App_main'

urlpatterns = [
    path('', views.home, name='home'),
    path('services/', views.services_views, name='services'),
    path('gallery/', views.gallery_view, name='gallery'),
    path('campaign/', views.campaign_views, name='campaign'),
    path('comment-send/', views.comment_views, name='comment-send'),
    path('user-dashboard/', views.user_dashboard, name='user-dashboard'),
    path('user-booking/', views.user_booking, name='user-booking'),
    path('booking-view/', views.booking_view, name='booking-view'),
    path('profile-view/', views.user_profile_view, name='profile-view'),
    path('update-profile/', views.user_edit_profile_view, name='update-profile'),
    path('parts-n-accessories/', views.parts_and_accessories_view, name='parts-n-accessories'),
    path('parts-n-accessories-single/<int:id>/', views.singleAccessory_view, name='parts-n-accessories-single'),
    path('customer-chat-room/', views.customer_chat_room, name='customer-chat-room'),
    path('customer-see-messages/<int:pk>/', views.customer_messages, name='customer-see-messages'),
    path('getMessages/<int:room>/', views.customer_get_messages, name='get-messages'),
    path('send-message/', views.customer_message_send, name='send-message'),
]

SmartGarageService_and_internal_messaging/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from SmartGarageService_and_internal_messaging import developers

urlpatterns = [
    # You shouldn't 
    path('developers/', developers.developersView, name='developers'),
    path('super-admin/', admin.site.urls),
    path('accounts/', include('App_auth.urls')),
    path('', include('App_main.urls')),
    path('admin/', include('App_admin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>FLOATINGMEND - Bike Repairing Booking Website</title>
    <style>
        :root {
            --primary: #FD5D14;
            --secondary: #FDBE33;
            --light: #F4F6F8;
            --dark: #040F28;
        }

        .bg-dark {
            background-color: #040F28 !important;
        }

        .navbar-dark .navbar-nav .nav-link {
            position: relative;
            padding: 15px 15px;
            font-size: 18px;
            text-transform: uppercase;
            color: var(--light);
            outline: none;
            transition: .5s;
        }

        .navbar-dark .navbar-nav .nav-link:hover,
        .navbar-dark .navbar-nav .nav-link.active {
            color: var(--primary);
        }

        #navbar-logo {
            display: none;
        }

        #id-signup-login-minimized {
            display: none;
            padding: 0 50px;
        }

        @media only screen and (max-width: 991px) {
            .navbar {
                height: 120px;
            }

            #navbar-logo {
                display: block;
            }

            #navbar-logo h1 span {
                font-size: 20px !important;
            }

            #id-signup-login-minimized {
                display: block;
            }

            .navbar-collapse {
                background-color: #040F28 !important;
                overflow-y: scroll;
                -ms-overflow-y: scroll;
                height: 300px;
            }
        }

        .navbar-collapse {
            background-color: #040F28 !important;
        }
    </style>
</head>
<body>
<!-- Top Start -->
<div class="container-fluid px-5 d-none d-lg-block" id="top-navbar">
    <div class="row gx-5">
        <div class="col-lg-4 text-center py-3">
            <div class="d-inline-flex align-items-center">
                <i class="bi bi-geo-alt fs-1 text-primary me-3"></i>
                <div class="text-start">
                    <a href="{% url 'App_main:home' %}" class="navbar-brand">
                        <h1 class="m-0 display-4" style="font-size: 32px; color: #173a56">
                            <img src="{% static 'img/logo.png' %}" alt="Logo" style="width: 65px; height: 45px;">
                            {#                            <i class="bi bi-building text-primary me-2"></i>#}
                            <span style="font-family: 'Monoton', cursive;">FLOATINGMEND</span>
                        </h1>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 text-center border-start border-end py-3"
             style="background-color: #FCE011; border-color: #FCE011;">
            <div class="d-inline-flex align-items-center">
                <i class="bi bi-envelope-open fs-1 text-primary me-3"></i>
                <div class="text-start">
                    {% if user.is_authenticated %}
                        <h6 class="text-uppercase fw-bold"
                            onclick="window.location.href='{% url "App_main:booking-view" %}'"
                            style="cursor: pointer;">
                            <i class="fa fa-hand-pointer-o" style="color: firebrick"></i>
                            BOOKING ONLINE
                        </h6>
                    {% else %}
                        <h6 class="text-uppercase fw-bold"
                            onclick="alert('Please Login!')"
                            style="cursor: pointer;">
                            <i class="fa fa-hand-pointer-o" style="color: firebrick"></i>
                            BOOKING ONLINE
                        </h6>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg-4 text-center py-3">
            <div class="d-inline-flex align-items-center">
                <i class="bi bi-phone-vibrate fs-1 text-primary me-3"></i>
                <div class="text-start">
                    {% if user.is_authenticated %}
                        <h6 class="text-uppercase fw-bold" style="cursor: pointer;"
                            onclick="window.location.href='{% url "App_main:profile-view" %}'">
                            <i class="fas fa-user"></i>
                            &nbsp; User
                        </h6>
                        <span style="cursor: pointer;" onclick="window.location.href='{% url "App_auth:logout" %}'">
                            <i class="fas fa-sign-out-alt"></i>
                            Logout
                        </span>
                    {% else %}
                        <h6 class="text-uppercase fw-bold" style="cursor: pointer;"
                            data-bs-toggle="modal" data-bs-target="#signupFormModal">
                            <i class="fa fa-user-plus"></i>
                            SIGNUP
                        </h6>
                        <span style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#signinFormModal">
                            <i class="fas fa-fingerprint"></i>
                            SIGN IN
                        </span>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Topbar End -->
<!-- Navbar Start -->
<div class="container-fluid sticky-top bg-dark w-100">
    <nav class="navbar navbar-expand-lg bg-dark bg-light-radial navbar-dark py-3 py-lg-0">
        <a href="{% url 'App_main:home' %}" class="navbar-brand" id="navbar-logo">
            <h1 class="m-0 display-4" style="font-size: 35px; color: #173a56;">
                <img src="{% static 'img/logo.png' %}" alt="Logo" style="width: 65px; height: 45px;">
                {#                            <i class="bi bi-building text-primary me-2"></i>#}
                <span style="font-family: 'Monoton', cursive; color:#ffffff;">FLOATINGMEND</span>
            </h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav mx-auto py-0">
                <a href="{% url 'App_main:services' %}" id="id-service" class="nav-item nav-link">Repair & Service</a>
                <a href="{% url 'App_main:parts-n-accessories' %}" id="id-parts" class="nav-item nav-link">Parts &
                    Accessories</a>
                <a href="{% url 'App_main:gallery' %}" id="id-gallery" class="nav-item nav-link">Workshop Gallery</a>
                <a href="{% url 'App_main:campaign' %}" id="id-about" class="nav-item nav-link">About & Contact</a>
                {#                <div class="nav-item dropdown">#}
                {#                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>#}
                {#                    <div class="dropdown-menu m-0">#}
                {#                        <a href="#" class="dropdown-item">Our Project</a>#}
                {#                        <a href="#" class="dropdown-item">The Team</a>#}
                {#                        <a href="#" class="dropdown-item">Testimonial</a>#}
                {#                        <a href="#" class="dropdown-item">Blog Grid</a>#}
                {#                        <a href="#" class="dropdown-item">Blog Detail</a>#}
                {#                    </div>#}
                {#                </div>#}
                {#                <a href="" class="nav-item nav-link bg-primary text-white px-5 ms-3 d-none d-lg-block">Get A Quote <i#}
                {#                        class="bi bi-arrow-right"></i></a>#}
                <p id="id-signup-login-minimized">
                    <a href="" style="float:left;" data-bs-toggle="modal" data-bs-target="#signupFormModal">Signup</a>
                    <a href="" style="float:right;" data-bs-toggle="modal" data-bs-target="#signinFormModal">Login</a>
                </p>
            </div>
        </div>
    </nav>
</div>
<!-- Navbar End -->
{% block main %}
{% endblock %}
{% include 'footer.html' %}

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="https://fonts.googleapis.com/css?family=Lato|Nanum+Gothic:700|Raleway&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css" rel="stylesheet">

    <style>
        html {
            scroll-behavior: smooth;
        }

        section {
            text-align: justify;
            padding: 0 2em 2em;
        }

        h1 {
            text-align: center;
            font-family: roboto;
            font-weight: 400;
            font-size: 35px;
            color: #656565;
        }

        .dummy-text {
            color: #3c3b3b;
            font-family: lato;
            font-size: 20px;
            line-height: 1.5;
        }

        .col-6 {
            width: 50%;
            display: inline-table;
        }

        footer {
            background-color: #040F28 !important;
            padding: 3em 4em 2em;
        }

        footer .logo {
            color: #fff;
            font-size: 28px;
            font-family: roboto;
        }

        footer .row {
            margin: 2em 0;
            font-family: lato;
            color: #fff;
            position: relative;
            border-bottom: 1px solid #cecece;
        }

        .footer-toggle {
            display: none;
        }

        .link-cat {
            cursor: pointer;
        }

        footer ul {
            padding: 0;
            -webkit-transition: all .3s ease-in-out;
            transition: all .3s ease-in-out;
        }

        footer ul li {
            list-style-type: none;
            padding: 0;
            -webkit-transition: all .5s ease-in-out;
            transition: all .5s ease-in-out;
            line-height: 2;
        }

        footer .footer-cat, #newsletter span {
            font-size: 20px;
        }

        .footer-cat-links a {
            color: #cecece;
            text-decoration: none;
            position: relative;
        }

        .footer-cat-links.active > li a {
            pointer-events: auto;
        }

        .footer-cat-links a:after {
            top: 21px;
            content: "";
            display: block;
            height: 2px;
            left: 50%;
            position: absolute;
            width: 0;
            background: #fff;

            -webkit-transition: width 0.3s ease 0s, left 0.3s ease 0s;
            transition: width 0.3s ease 0s, left 0.3s ease 0s;
        }

        .footer-cat-links a:hover:after, .footer-cat-links a:focus:after {
            width: 100%;
            left: 0;
        }

        footer #subscribe {
            margin: 20px 0px 30px;
        }

        input#subscriber-email {
            outline: none;
            padding: 8px;
            background: #212121;
            border: 1px solid #cecece;
            color: #cecece;
            border-radius: 4px 0px 0px 4px;
        }

        input#subscriber-email::-webkit-input-placeholder {
            color: rgb(202, 196, 196);
        }

        input#subscriber-email:-ms-input-placeholder {
            color: #cecece;
        }

        input#subscriber-email::-ms-input-placeholder {
            color: #cecece;
        }

        input#subscriber-email::placeholder {
            color: #cecece;
        }

        .col-3 {
            display: inline-table;
            width: 25%;
        }

        .col-3#newsletter {
            width: 24%
        }

        .col-3#newsletter #btn-scribe {
            margin-left: -4px;
            border: 1px solid #cecece;
            border-radius: 0px 4px 4px 0;
            padding: 8px 5px;
            background-color: #e2e2e2;
            color: #212121;
            cursor: pointer;
        }

        .social-2 {
            display: none;
        }

        .social-links {
            bottom: 44px;
            position: absolute;
            left: 0;
        }

        .social-links a {
            color: #fff;
            font-size: 20px;
            border: 1px solid;
            border-radius: 20px;
            padding: 6px;

            -webkit-transition: all .2s ease-in;
            transition: all .2s ease-in;
        }

        .social-links a:not(:last-child) {
            margin-right: 10px;
        }

        .social-links a:hover, .social-links a:focus {
            background-color: #212121;
        }

        .social-links a i {
            width: 25px;
            height: 25px;
            text-align: center;
        }

        #newsletter #address li:not(:first-child) {
            padding: 20px 0;
        }

        #newsletter #address li i {
            font-size: 45px;
            width: auto;
            padding: 5px;
        }

        #newsletter #address li div {
            color: #cecece;
            font-size: 14px;
            width: 80%;
            text-align: left;
            float: right;
            line-height: 1.3;
        }

        #copyright {
            text-align: center;
            color: #fff;
            font-family: lato;
        }

        #owner {
            text-align: center;
            padding: 20px 0 0px;
            color: #fff;
            font-family: lato;
        }

        #owner a {
            color: #fff;
        }

        /* iPads to Smartphone for Common Elements ----------- */
        @media only screen and (max-width: 1024px) {

            .social-links a {
                display: none;
            }

            .col-3 {
                display: block;
                width: 100%;
                padding-bottom: 1em;
                position: relative;
            }

            .col-3#newsletter {
                width: 100%;
                position: relative;
                padding-bottom: 0;
                padding-top: 1em;
            }

            footer .footer-cat {
                margin-left: 25px;
            }

            .footer-toggle, .footer-toggle::after {
                background: #fff;
                height: 2px;
                width: 15px;
                position: absolute;
                display: block;
                -webkit-transition: all .4s ease-in;
                transition: all .4s ease-in;
            }

            .footer-toggle {
                top: 11px;
                cursor: pointer;
            }

            .footer-toggle::after {
                content: '';
                -webkit-transform: rotate(90deg);
                transform: rotate(90deg);
            }

            .btnActive .footer-toggle::after {
                -webkit-transform: rotate(0deg);
                transform: rotate(0deg);
            }

            .footer-cat-links {
                margin: 0 0em 0px 1.6em;
            }

            .footer-cat-links a {
                pointer-events: none;
            }

            .footer-cat-links li {
                line-height: 0;
                opacity: 0;
            }

            .footer-cat-links.active > li {
                line-height: 2;
                opacity: 1;
            }

            .social-1 {
                display: none !important;
            }

            .social-2 {
                display: block;
                position: absolute;
                top: 7.5em;
                bottom: 0px;
                height: 20px;
                padding-bottom: 1.5em;
                width: 100%;
            }

            #address {
                margin-top: 6em;
            }

            #newsletter #address li i {
                width: auto;
            }

            #newsletter #address li div {
                font-size: 14px;
                width: auto;
                text-align: left;
                float: none;
                line-height: 2;
                display: inline-block;
                padding: 10px 0 15px;
            }

            #newsletter #address li div:last-child {
                padding-bottom: 0;
            }

            #newsletter #address li:not(:first-child) {
                padding: 20px 0 0;
            }
        }

        /* iPads (portrait)----------- */
        @media only screen and (min-width: 768px) and (max-width: 1024px) and (orientation: portrait) {

            footer {
                padding-right: 3em;
                padding-left: 3em;
            }

            .col-3 {
                display: block;
                width: 100%;
                padding-bottom: 1em;
            }
        }

        /* iPads (landscape) ----------- */
        @media only screen and (min-width: 768px) and (max-width: 1024px) and (orientation: landscape) {

            section {
                padding-bottom: 3em;
            }

            .sec-heading {
                padding: 1em 0;
            }

            .col-3 {
                display: block;
                width: 100%;
                padding-bottom: 1em;
            }
        }

        /* Mini Tablet ----------- */
        @media only screen and (max-width: 600px) {

            .col-3 {
                display: block;
                width: 100%;
                padding-bottom: 1em;
            }

            .col-6 {
                width: 100%;
                display: block;
            }

            footer {
                padding: 3em 2em 2em;
            }
        }

        /* Smartphones (portrait and landscape) ----------- */
        @media only screen and (max-width: 480px) {

            .col-6 {
                width: 100%;
                display: block;
            }

            footer {
                padding-right: 1em;
                padding-left: 1em;
            }
        }
    </style>
</head>
<body>

<footer>
    <div>
        <span class="logo" style="font-family: 'Monoton', cursive;">Smart Garage BD</span>
    </div>

    <div class="row">
        <div class="col-3">
            <div class="link-cat" onclick="footerToggle(this)">
                <span class="footer-toggle"></span>
                <span class="footer-cat">Solutions</span>
            </div>
            <ul class="footer-cat-links">
                <li><a href=""><span>Bike Service</span></a></li>
                <li><a href=""><span>Bike Accessories</span></a></li>
                <li><a href=""><span>Home Bike Service</span></a></li>
            </ul>
        </div>
        <div class="col-3">
            <div class="link-cat" onclick="footerToggle(this)">
                <span class="footer-toggle"></span>
                <span class="footer-cat">Industries</span>
            </div>
            <ul class="footer-cat-links">
                <li><a href=""><span>Booking</span></a></li>
                <li><a href=""><span>Login</span></a></li>
                <li><a href=""><span>Sign up</span></a></li>
                <li><a href=""><span>Profile</span></a></li>
                <li><a href=""><span>Dashboard</span></a></li>
            </ul>
        </div>
        <div class="col-3">
            <div class="link-cat" onclick="footerToggle(this)">
                <span class="footer-toggle"></span>
                <span class="footer-cat">Quick Links</span>
            </div>
            <ul class="footer-cat-links">
                <li><a href=""><span>Repair & Services</span></a></li>
                <li><a href=""><span>Parts & Accessories</span></a></li>
                <li><a href=""><span>Workshop</span></a></li>
                <li><a href=""><span>About & Contact</span></a></li>
            </ul>
        </div>
        <div class="col-3" id="newsletter">
            <div class="social-links social-2">
                <a href=""><i class="fab fa-facebook-f"></i></a>
                <a href=""><i class="fab fa-twitter"></i></a>
                <a href=""><i class="fab fa-linkedin-in"></i></a>
                <a href=""><i class="fab fa-instagram"></i></a>
                <a href=""><i class="fab fa-reddit-alien"></i></a>
            </div>

            <div id="address">
                <span>Office Location</span>
                <ul>
                    <li>
                        <i class="far fa-building"></i>
                        <div>Dhaka, Bangladesh<br/>
                            Office [house no], [ABCD tower], [Road Number], [City]
                        </div>
                    </li>
                </ul>
            </div>

        </div>
    </div>
    <div id="copyright">
        &copy; All Rights Reserved 2022
    </div>
    <div id="owner">
           <span>
               Designed by <a href="#">Rajon and Sanjida</a>
           </span>
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
    function footerToggle(footerBtn) {
        $(footerBtn).toggleClass("btnActive");
        $(footerBtn).next().toggleClass("active");
    }
</script>
</body>
</html>

templates/testing_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

</body>
</html>