App_auth/urls.py
from django.urls import path
from App_auth.views import *

app_name = 'App_auth'

urlpatterns = [
    path('register/', registerView, name='register'),
    path('login/', loginView, name='login'),
    path('logout/', logoutView, name='logout'),
]

App_main/urls.py
from django.urls import path
from App_main import views

app_name = 'App_main'

urlpatterns = [
    path('', views.home, name='home'),
    path('services/', views.services_views, name='services'),
    path('gallery/', views.gallery_view, name='gallery'),
    path('campaign/', views.campaign_views, name='campaign'),
    path('comment-send/', views.comment_views, name='comment-send'),
    path('user-dashboard/', views.user_dashboard, name='user-dashboard'),
    path('user-booking/', views.user_booking, name='user-booking'),
    path('booking-view/', views.booking_view, name='booking-view'),
    path('profile-view/', views.user_profile_view, name='profile-view'),
    path('update-profile/', views.user_edit_profile_view, name='update-profile'),
    path('parts-n-accessories/', views.parts_and_accessories_view, name='parts-n-accessories'),
    path('parts-n-accessories-single/<int:id>/', views.singleAccessory_view, name='parts-n-accessories-single'),
    path('customer-chat-room/', views.customer_chat_room, name='customer-chat-room'),
    path('customer-see-messages/<int:pk>/', views.customer_messages, name='customer-see-messages'),
    path('getMessages/<int:room>/', views.customer_get_messages, name='get-messages'),
    path('send-message/', views.customer_message_send, name='send-message'),
]

SmartGarageService_and_internal_messaging/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from SmartGarageService_and_internal_messaging import developers

urlpatterns = [
    # You shouldn't 
    path('developers/', developers.developersView, name='developers'),
    path('super-admin/', admin.site.urls),
    path('accounts/', include('App_auth.urls')),
    path('', include('App_main.urls')),
    path('admin/', include('App_admin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


App_main/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _
from io import BytesIO
from django.core.files import File


# Create your models here.
class ServicesModel(models.Model):
    name = models.CharField(max_length=100)
    cost = models.IntegerField()
    details = models.TextField()
    logo = models.ImageField(upload_to='service_logo/', verbose_name=_("service_logo"))
    service_details_image = models.ImageField(upload_to='service_details_image/',
                                              verbose_name=_("service_details_image"))
    status = models.BooleanField(default=True)

    # def save(self, *args, **kwargs):
    #     new_logo = compress(self.logo)
    #     self.logo = new_logo
    #     new_service_image = compress(self.service_details_image)
    #     self.service_details_image = new_service_image
    #     super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"


service_type_choice_box = (
    ('Home Service', 'Home Service'),
    ('Go to Workshop', 'Go to Workshop'),
)


class BookingModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Booking_user')
    location = models.CharField(max_length=200)
    bike_type = models.CharField(max_length=200)
    service_name = models.ForeignKey(ServicesModel, on_delete=models.CASCADE, related_name='service_name')
    service_type = models.CharField(choices=service_type_choice_box, max_length=50)
    contact_number = models.CharField(max_length=20)
    booking_date = models.DateTimeField()
    created_date = models.DateTimeField(auto_now=True)
    additional_services = models.TextField()
    Total_cost = models.IntegerField(blank=True)
    booking_status = (
        ('Service Processing', 'Service Processing'),
        ('Service Accepted', 'Service Accepted'),
        ('Service Confirmed', 'Service Confirmed'),
        ('Service Provided', 'Service Provided'),
        ('Service Rejected', 'Service Rejected'),
    )
    status = models.CharField(choices=booking_status, max_length=20, default='Service Processing')


class CampaignModel(models.Model):
    cam_title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='campaign_uploads/')
    details = models.TextField()
    status = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.cam_title}"


class CommentOnCampaign(models.Model):
    name = models.CharField(max_length=100)
    mobile = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    pincode = models.CharField(max_length=6)
    special_brands = models.TextField()
    comment = models.TextField()


class GalleryModel(models.Model):
    image = models.ImageField(upload_to='gallery_image/')
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=100)
    details = models.TextField()


class Parts_n_Accessories_Model(models.Model):
    name = models.CharField(max_length=100)
    specifications = models.TextField()
    type = models.CharField(max_length=100)
    description = models.TextField()
    price = models.PositiveIntegerField()
    product_image = models.ImageField(upload_to='productImage/')


class ChatRoom(models.Model):
    name = models.CharField(max_length=100)


class MessageModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    value = models.CharField(max_length=10000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    room = models.ForeignKey(ChatRoom, on_delete=models.DO_NOTHING)

App_main/forms.py
from django import forms
from App_main.models import *


class BookingModelForm(forms.ModelForm):
    booking_date = forms.CharField(widget=forms.TextInput(attrs={'type': 'date'}))
    contact_number = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Contact Number'}))

    class Meta:
        model = BookingModel
        exclude = ['user', 'service_name', 'Total_cost', 'status', 'additional_services']


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = CommentOnCampaign
        exclude = ['special_brands']


class CampaignModelForm(forms.ModelForm):
    class Meta:
        model = CampaignModel
        fields = "__all__"


class ServicesModelForm(forms.ModelForm):
    class Meta:
        model = ServicesModel
        exclude = ['details']


class ServicesUpdateModelForm(forms.ModelForm):
    class Meta:
        model = ServicesModel
        exclude = ['name', 'details']


class GalleryModelForm(forms.ModelForm):
    class Meta:
        model = GalleryModel
        fields = '__all__'

App_main/views.py
import json

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from itertools import chain

from App_admin.views import is_customer
from App_auth.forms import SignupForm, ProfileModelForm, AddressModelForm
from App_auth.models import ProfileModel, AddressModel
from App_main.models import *
from App_main.forms import *


# Create your views here.
def loginForm_():
    loginForm = AuthenticationForm()
    loginForm.fields['username'].widget.attrs['placeholder'] = "Username"
    loginForm.fields['password'].widget.attrs['placeholder'] = "Password"
    return loginForm


def totalCostForServices(thisList, total_cost):
    if len(thisList) == 0:
        return total_cost
    else:
        if ServicesModel.objects.filter(name=thisList[0]).exists():
            total_cost += ServicesModel.objects.get(name=thisList[0]).cost
        thisList.remove(thisList[0])
        return totalCostForServices(thisList, total_cost)


def home(request):
    services = ServicesModel.objects.filter(status=True)
    parts = Parts_n_Accessories_Model.objects.all()
    bookingForm = BookingModelForm()
    loginForm = AuthenticationForm()
    loginForm.fields['username'].widget.attrs['placeholder'] = "Phone Number"
    loginForm.fields['password'].widget.attrs['placeholder'] = "Password"
    signupForm = SignupForm()
    if request.method == 'POST':
        # Total Cost and additional Services
        additionalList = request.POST.getlist('additional-services')
        mainServ = request.POST.get('service')
        additionalList.remove(mainServ)
        mainService = services.get(name=mainServ)
        # End
        bookingForm = BookingModelForm(request.POST)
        if bookingForm.is_valid():
            thisForm = bookingForm.save(commit=False)
            thisForm.service_type = mainService
            thisForm.additional_services = ", ".join(additionalList)
            thisForm.user = request.user
            thisForm.Total_cost = totalCostForServices(additionalList, mainService.cost)
            thisForm.save()

            return HttpResponseRedirect(reverse('App_main:home'))

    content = {
        'services': services,
        'bookingForm': bookingForm,
        'loginForm': loginForm,
        'signupForm': signupForm,
        'parts': parts,
    }
    return render(request, 'App_main/home.html', context=content)


def services_views(request):
    services = ServicesModel.objects.filter(status=True)
    content = {
        'services': services,
        'loginForm': loginForm_(),
    }
    return render(request, 'App_main/service.html', context=content)


def campaign_views(request):
    content = {
        'loginForm': loginForm_(),
    }
    return render(request, 'App_main/campaign.html', context=content)


@login_required
def booking_view(request):
    bookingForm = BookingModelForm()
    services = ServicesModel.objects.all()
    if request.method == 'POST':
        # Total Cost and additional Services
        additionalList = request.POST.getlist('additional-services')
        mainServ = request.POST.get('main-service')
        if mainServ in additionalList:
            additionalList.remove(mainServ)
        mainService = services.get(name=mainServ)
        # End
        bookingForm = BookingModelForm(data=request.POST)
        if bookingForm.is_valid():
            thisForm = bookingForm.save(commit=False)
            thisForm.service_name = mainService
            thisForm.additional_services = ", ".join(additionalList)
            thisForm.user = request.user
            all_cost = totalCostForServices(additionalList, mainService.cost)
            thisForm.Total_cost = all_cost
            thisForm.save()
            return HttpResponseRedirect(reverse('App_main:user-booking'))
    content = {
        'bookingForm': bookingForm,
        'services': services,
    }
    return render(request, 'App_main/bookings.html', context=content)


def comment_views(request):
    if request.method == 'POST':
        form = CommentModelForm(data=request.POST)
        if form.is_valid():
            thisForm = form.save(commit=False)
            thisForm.special_brands = request.POST.getlist('brands')
            thisForm.save()
            return HttpResponseRedirect(reverse('App_main:campaign'))


@login_required
def user_dashboard(request):
    return render(request, 'App_main/dashboard.html')


@login_required
def user_booking(request):
    myBookings = BookingModel.objects.filter(user=request.user)
    requested = BookingModel.objects.filter(user=request.user, status="Service Processing")
    accepted = BookingModel.objects.filter(user=request.user, status="Service Accepted")
    confirmed = BookingModel.objects.filter(user=request.user, status="Service Confirmed")
    ready = BookingModel.objects.filter(user=request.user, status="Service Provided")
    rejected = BookingModel.objects.filter(user=request.user, status="Service Rejected")

    content = {
        'requested': requested,
        'accepted': accepted,
        'confirmed': confirmed,
        'ready': ready,
        'rejected': rejected,
        'ongoing': confirmed,
    }
    return render(request, 'App_main/user_bookings_view.html', context=content)


@login_required
def user_profile_view(request):
    my_chat_room = ChatRoom.objects.get(name=request.user.username)
    try:
        profile = ProfileModel.objects.get(user=request.user)
    except:
        profile = None
    content = {
        'profile': profile,
        'myChatRoom': my_chat_room
    }
    return render(request, 'App_main/profile_view.html', context=content)


@login_required
def user_edit_profile_view(request):
    try:
        profileInstance = ProfileModel.objects.get(user=request.user)
    except:
        profileInstance = None
        address = None
    ProfileForm = ProfileModelForm(instance=profileInstance)
    if request.method == 'POST':
        ProfileForm = ProfileModelForm(request.POST, request.FILES)
        if ProfileForm.is_valid():
            thisProfile = ProfileForm.save(commit=False)
            thisProfile.user = request.user
            thisProfile.save()
    content = {
        'ProfileForm': ProfileForm,
    }
    return render(request, 'App_main/update_user_profile.html', context=content)


def parts_and_accessories_view(request):
    parts = Parts_n_Accessories_Model.objects.all()
    content = {
        'parts_n_accessories': parts,
    }
    return render(request, 'App_main/parts_and_accessories.html', context=content)


def singleAccessory_view(request, id):
    part = Parts_n_Accessories_Model.objects.get(id=id)
    content = {
        'part': part,
    }
    return render(request, 'App_main/parts_and_accessories_single.html', context=content)


def gallery_view(request):
    galleryObj = GalleryModel.objects.all()
    content = {
        'galleryObj': galleryObj,
    }
    return render(request, 'App_main/gallery.html', context=content)


# # API View
# @permission_classes([AllowAny, ])
# @api_view(['GET', 'POST', ])
# def homeAPI(request):
#     if request.method == 'GET':
#         service = ServicesModel.objects.filter(status=True)
#         serializer = ServicesModelSerializer(service, many=True)
#         return Response(serializer.data)


# class HomeAPIView(ListCreateAPIView):
#     permission_classes = [IsAuthenticated, ]
#     queryset = BookingModel.objects.all()
#     serializer_class = BookingModelSerializer

#     def perform_create(self, serializer):
#         service = self.request.data['service']
#         sType = ServicesModel.objects.get(name=service)
#         add_services = str(self.request.data['additional-services'])
#         add_services = add_services.split(", ")
#         newList, total_cost = totalCostForServices(add_services, sType.cost)
#         _additional_services = "".join(newList)
#         return serializer.save(user=self.request.user, service_type=sType, Total_cost=total_cost,
#                                additional_services=_additional_services)

#     def create(self, request, *args, **kwargs):
#         serializer = self.get_serializer(data=request.data)
#         serializer.is_valid(raise_exception=True)
#         self.perform_create(serializer)
#         headers = self.get_success_headers(serializer.data)
#         return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

#     def list(self, request, *args, **kwargs):
#         queryset = self.filter_queryset(self.get_queryset())

#         page = self.paginate_queryset(queryset)
#         if page is not None:
#             serializer = self.get_serializer(page, many=True)
#             return self.get_paginated_response(serializer.data)

#         serializer = BookingModelSerializerFull(queryset, many=True)
#         return Response(serializer.data)


# class ServicesAPIView(ListAPIView):
#     permission_classes = [AllowAny, ]
#     queryset = ServicesModel.objects.all()
#     serializer_class = ServicesModelSerializer

#     def list(self, request, *args, **kwargs):
#         queryset = self.filter_queryset(self.get_queryset())

#         page = self.paginate_queryset(queryset)
#         if page is not None:
#             serializer = self.get_serializer(page, many=True)
#             return self.get_paginated_response(serializer.data)

#         serializer = ServicesModelSerializer(queryset, many=True)
#         return Response(serializer.data)

#     def get_queryset(self):

templates/App_main/bookings.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block main %}
    <style>
        label {
            font-weight: 400;
            font-size: 15px;
            padding-left: 10px;
            color: rgb(82, 82, 82);
        }

        input, #id_service_type {
            color: rgba(0, 0, 0, 0.65);
            background-color: rgb(255, 255, 255);
            height: auto;
            padding: 6px 11px;
            font-size: 16px;
            width: 100%;
            border-radius: 6px;
            border: 1px solid green;
            cursor: pointer;
        }
    </style>
    {% block extra_toggle_button %}
        <button class="navbar-toggler" type="button" onclick="toggleSlider()">
            <span class="navbar-toggler-icon"></span>
        </button>
    {% endblock %}
    {% include 'App_main/customer_dashboard_base.html' %}
    <div class="container">
        <div id="main">
            <div class="service-div">
                <div class="container">
                    <div class="container">
                        <div class="row justify-content-center">
                            <form action="{% url 'App_main:booking-view' %}" method="post">
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <label for="#id_location">Location</label>
                                            {{ bookingForm.location }}
                                        </div>
                                        <div class="col-md-3">
                                            <label for="#id_location">Bike Type</label>
                                            {{ bookingForm.bike_type }}
                                        </div>
                                        <div class="col-md-3">
                                            <label for="#id_location">Booking Date</label>
                                            {{ bookingForm.booking_date }}
                                        </div>
                                        <div class="col-md-3">
                                            <label for="#id_contact_number">Contact Number</label>
                                            {{ bookingForm.contact_number }}
                                        </div>
                                    </div>
                                    <div class="row mt-2">
                                        <div class="col-md-3">
                                            <legend>Main Services</legend>
                                            {% for service in services %}
                                                <div class="form-check">
                                                    <input class="form-check-input" type="radio" name="main-service"
                                                           id="flexRadioDefault1-{{ service.id }}"
                                                           value="{{ service }}">
                                                    <label class="form-check-label"
                                                           for="flexRadioDefault1-{{ service.id }}">
                                                        {{ service }}
                                                    </label>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="col-md-3">
                                            <legend>Additional Services</legend>
                                            {% for service in services %}
                                                <div class="form-check">
                                                    <input class="form-check-input" type="checkbox"
                                                           value="{{ service }}"
                                                           id="flexCheckDefault-{{ service.id }}"
                                                           name="additional-services">
                                                    <label class="form-check-label"
                                                           for="flexCheckDefault-{{ service.id }}">
                                                        {{ service }}
                                                    </label>
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="col-md-3">
                                            <legend>Service Type</legend>
                                            {{ bookingForm.service_type }}
                                        </div>
                                    </div>
                                </fieldset>
                                <div class="form-group mt-3 text-end">
                                    <button class="btn btn-success" type="submit">Submit Booking</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        var mini = true;
        let counter = 0;
        let sideBar = document.getElementById("mySidebar");
        let main_bar = document.getElementById("main");

        function toggleSidebar() {
            if (mini) {
                sideBar.style.width = "250px";
                main_bar.style.marginLeft = "250px";
                this.mini = false;
            } else {
                sideBar.style.width = "85px";
                main_bar.style.marginLeft = "85px";
                this.mini = true;
            }
        }

        function toggleSlider() {
            if (counter === 0) {
                sideBar.style.display = 'block';
                sideBar.style.width = "250px";
                counter = 1;
            } else {
                sideBar.style.display = 'none';
                counter = 0;
            }
        }
    </script>
{% endblock %}

templates/App_main/customer_dashboard_base.html
<style>
    footer {
        margin-left: 80px;
    }

    .sidebar {
        height: 100%;
        width: 85px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: rgb(34, 34, 34);
        transition: 0.5s;
        overflow-x: hidden;
        padding-top: 60px;
        white-space: nowrap;
        margin-top: 135px;
    }

    .sidebar a {
        padding: 8px 8px 8px 32px;
        text-decoration: none;
        font-size: 13px;
        color: #ffffff;
        display: block;
    }

    .-active {
        background-color: rgb(228, 107, 51);
    }

    .sidebar a:hover {
        color: #f1f1f1;
    }

    main .sidebar {
        position: absolute;
        top: 0;
        right: 25px;
        font-size: 36px;
        margin-left: 50px;
    }

    .material-icons,
    .icon-text {
        vertical-align: middle;
    }

    .material-icons {
        padding-bottom: 3px;
        margin-right: 30px;
    }

    #main {
        padding: 16px;
        margin-left: 85px;
        transition: margin-left 0.5s;
    }

    @media screen and (max-height: 450px) {
        .sidebar {
            padding-top: 15px;
        }

        .sidebar a {
            font-size: 13px;
            color: #ffffff;
        }

        #main {
            padding: 16px 0;
            margin-left: 0;
        }
    }

    @media screen and (max-width: 767px) {
        .sidebar {
            padding-top: 15px;
            display: none;
        }

        .sidebar a {
            font-size: 13px;
            color: #ffffff;
        }
    }

    @media screen and (min-width: 768px) {
        .sidebar {
            padding-top: 15px;
            display: block;
        }
    }

    .service-box {
        text-align: center;
        background: rgb(255, 255, 255);
        padding: 10px;
        margin-bottom: 30px;
        max-width: 250px;
        width: auto;
        height: 85px;
        cursor: pointer;
        box-shadow: rgb(170 178 189) 0 3px 2px;
        border: 1px solid rgb(204, 204, 204);
        border-radius: 8px;
    }

    .service-box .plain-text {
        font-family: "Lato", sans-serif !important;
        font-size: 14px !important;
        font-weight: 400 !important;
    }

    .service-box-icon img {
        vertical-align: middle !important;
        width: 24px;
        height: 24px;
    }
</style>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div id="mySidebar" class="sidebar" onmouseover="toggleSidebar()" onmouseout="toggleSidebar()">
    <div class="menu-item">
        <a href="{% url 'App_main:user-dashboard' %}" id="id-dashboard">
                <span>
                    <i class="material-icons">D</i>
                    <span class="icon-text">
                        Dashboard
                    </span>
                </span>
        </a>
        <br>
    </div>
    <div class="menu-item">
        <a href="{% url 'App_main:user-booking' %}" id="id-bookings">
                <span>
                    <i class="material-icons">book</i>
                    <span class="icon-text">
                        Bookings
                    </span>
                </span>
        </a>
        <br>
    </div>
    <div class="menu-item" style="display:none;">
        <a href="#" id="id-invoices">
                <span>
                    <i class="material-icons">receipt</i>
                    <span class="icon-text">
                        Invoices
                    </span>
                </span>
        </a><br>
    </div>
    <div class="menu-item">
        <a href="#" id="id-warranty">
                <span>
                    <i class="material-icons">person</i>
                    <span class="icon-text">
                        Warranty
                    </span>
                </span>
        </a>
        <br>
    </div>
    <div class="menu-item">
        {% if profile %}
            <a href="{% url 'App_main:customer-see-messages' pk=myChatRoom.id %}" id="id-chat">
            <span>
                <i class="material-icons">message</i>
                <span class="icon-text">
                    Message
                </span>
            </span>
            </a>
            <br>
        {% endif %}
    </div>
    <div class="menu-item">
        <a href="#" id="id-contact-us">
            <span>
                <i class="material-icons">phone</i>
                <span class="icon-text">
                    Contact us
                </span>
            </span>
        </a>
    </div>
</div>

<script>
    let mini_ = true;
    let cnt = 0;
    let sideBar_ = document.getElementById("mySidebar");
    let main_bar_ = document.getElementById("main");

    function toggleSidebar() {
        if (mini_) {
            sideBar_.style.width = "250px";
            this.mini_ = false;
        } else {
            sideBar_.style.width = "85px";
            this.mini_ = true;
        }
    }

    function toggleSlider() {
        if (cnt === 0) {
            sideBar_.style.display = 'block';
            sideBar_.style.width = "250px";
            cnt = 1;
        } else {
            sideBar_.style.display = 'none';
            cnt = 0;
        }
    }
</script>

templates/App_main/parts_and_accessories.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <link rel="stylesheet" href="{% static 'css/basicx.css' %}">

    <style>
        .maloy-card p.text-left {
            font: 14px Lato, sans-serif;
            font-weight: 500;
            cursor: pointer;
        }

        .maloy-card:hover {
            box-shadow: 0 5px 5px #888888;
            transition: .5s;
            border-radius: 5px;
        }

        .image-container {
            margin: 40px 0;
            width: auto;
            height: 150px;
        }

        .image-responsive {
            width: 100%;
            height: auto;
        }
    </style>

    <div class="container all-services">
        <h1 class="smart-services-header">
            Parts and Accessories
        </h1>
        <div class="row">
            {% for part in parts_n_accessories %}
                <div class="col-md-3 col-sm-12 card-container maloy-card">
                    <div style="text-align: center;" class="image-container">
                        <img class="image-responsive" src="{{ part.product_image.url }}" alt="Product Image">
                    </div>
                    <div class="container">
                        <p class="text-left"
                           onclick="window.location.href='{% url "App_main:parts-n-accessories-single" id=part.id %}'">
                            {{ part.name }}
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <script>
        let dumpedData = JSON.stringify({{ dictionJson }});
        console.log(dumpedData);
    </script>
{% endblock %}